pub mod account_repository;
pub mod admin_repository;
pub mod customer_repository;
pub mod fixed_deposit_repository;
pub mod home_loan_repository;
pub mod loan_repository;
pub mod product_repository;
pub mod transaction_repository;
pub mod user_repository;
