use crate::controllers;
use actix_web::{guard, web};

pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("")
            .guard(guard::Host("onboarding.localhost"))
            .route("/", web::get().to(controllers::onboarding_entry_redirect))
            .route("/onboarding", web::get().to(controllers::onboarding_entry_redirect))
            .route("/onboarding/{path}", web::get().to(controllers::onboarding))
            .route("/account-creation/init", web::get().to(controllers::account_creation_init))
            .route("/account-creation", web::get().to(controllers::account_creation))
            .route("/account-creation", web::post().to(controllers::account_creation_submit))
            .service(
                web::scope("/api/onboarding/actions")
                    .route("/submit-step1", web::post().to(controllers::step1_post))
                    .route("/submit-step2", web::post().to(controllers::step2_post))
                    .route("/submit-step3", web::post().to(controllers::step3_post))
                    .route("/submit-step4", web::post().to(controllers::step4_post))
                    .route("/submit", web::post().to(controllers::submit)),
            ),
    )
    .service(
        web::scope("")
            .guard(guard::Host("admin.localhost"))
            .route("/", web::get().to(controllers::admin_dashboard))
            .route("/login", web::get().to(controllers::admin_login_page))
            .route("/login", web::post().to(controllers::admin_login))
            .route("/logout", web::get().to(controllers::admin_logout))
            .route("/dashboard", web::get().to(controllers::admin_dashboard))
            .route("/signups", web::get().to(controllers::admin_signups_page))
            .route("/onboardings", web::get().to(controllers::admin_signups_page))
            .route("/staff", web::get().to(controllers::admin_staff_page))
            .route("/accounts", web::get().to(controllers::admin_customer_accounts_page))
            .route("/high-value-monitoring", web::get().to(controllers::admin_high_value_monitoring_page))
            .route("/high-value-monitoring/{id}/status", web::post().to(controllers::update_high_value_alert_status))
            .route("/audit-log", web::get().to(controllers::admin_audit_log_page))
            .route("/personal-loans", web::get().to(controllers::admin_personal_loans_page))
            .route("/home-loans", web::get().to(controllers::admin_home_loans_page))
            .route("/fixed-deposits", web::get().to(controllers::admin_fixed_deposits_page))
            .route("/fixed-deposit-plans", web::get().to(controllers::admin_fixed_deposit_plans_page)),
    )
    .service(
        web::scope("")
            .route("/", web::get().to(controllers::home))
            .route("/banking", web::get().to(controllers::banking_page))
            .route("/security", web::get().to(controllers::security_page))
            .route("/about", web::get().to(controllers::about_page))
            .route("/faq", web::get().to(controllers::faq_page))
            .route("/contact", web::get().to(controllers::contact_page))
            .route("/onboarding", web::get().to(controllers::onboarding_entry_redirect))
            .route("/onboarding/{path}", web::get().to(controllers::onboarding))
            .route("/onboarding/{path}", web::post().to(controllers::onboarding))
            .route("/signup", web::get().to(controllers::legacy_signup_redirect))
            .route("/signup/{path}", web::get().to(controllers::legacy_signup_path_redirect))
            .route("/account-creation/init", web::get().to(controllers::account_creation_init))
            .route("/account-creation", web::get().to(controllers::account_creation))
            .route("/account-creation", web::post().to(controllers::account_creation_submit))
            .route("/api/account-creation/submit", web::post().to(controllers::account_creation_submit))
            .route("/login", web::get().to(controllers::login_page))
            .route("/login", web::post().to(controllers::login))
            .service(
                web::scope("/api/onboarding/actions")
                    .route("/submit-step1", web::post().to(controllers::step1_post))
                    .route("/submit-step2", web::post().to(controllers::step2_post))
                    .route("/submit-step3", web::post().to(controllers::step3_post))
                    .route("/submit-step4", web::post().to(controllers::step4_post))
                    .route("/submit", web::post().to(controllers::submit)),
            )
            .service(
                web::scope("/api/onboarding")
                    .route("/account", web::post().to(controllers::step1_post))
                    .route("/personal", web::post().to(controllers::step2_post))
                    .route("/contact", web::post().to(controllers::step3_post))
                    .route("/employment", web::post().to(controllers::step4_post))
                    .route("/submit", web::post().to(controllers::submit)),
            )
            .route("/logout", web::get().to(controllers::logout))
            .route("/403", web::get().to(controllers::forbidden))
            .service(
                web::scope("/customer")
                    .route("/dashboard", web::get().to(controllers::dashboard))
                    .route("/accounts/create", web::post().to(controllers::create_bank_account))
                    .route("/deposit", web::get().to(controllers::deposit_page))
                    .route("/deposit", web::post().to(controllers::deposit))
                    .route("/transfer", web::get().to(controllers::transfer_page))
                    .route("/transfer", web::post().to(controllers::transfer))
                    .route("/giro", web::get().to(controllers::giro_page))
                    .route("/giro", web::post().to(controllers::create_giro_arrangement))
                    .route("/giro/{id}/cancel", web::post().to(controllers::cancel_giro_arrangement))
                    .route("/transaction-controls", web::get().to(controllers::transaction_controls_page))
                    .route("/transaction-controls/limit", web::post().to(controllers::update_transaction_limit))
                    .route("/transaction-controls/money-lock", web::post().to(controllers::update_money_lock))
                    .route("/paynow", web::get().to(controllers::paynow_page))
                    .route("/paynow/register", web::post().to(controllers::register_paynow))
                    .route("/paynow/transfer", web::post().to(controllers::transfer_paynow))
                    .route("/cards", web::get().to(controllers::cards_page))
                    .route("/cards", web::post().to(controllers::create_card))
                    .route("/cards/{id}/freeze", web::post().to(controllers::freeze_card))
                    .route("/cards/{id}/activate", web::post().to(controllers::activate_card))
                    .route("/transactions", web::get().to(controllers::transactions))
                    .route("/statements", web::get().to(controllers::statements_page))
                    .route("/statements/download", web::get().to(controllers::download_statement_pdf))
                    .route("/loan-activity", web::get().to(controllers::loan_activity))
                    .route("/loan-log", web::get().to(controllers::loan_activity))
                    .route("/fixed-deposit-activity", web::get().to(controllers::fixed_deposit_activity))
                    .route("/fixed-deposit-log", web::get().to(controllers::fixed_deposit_activity))
                    .route("/loans", web::get().to(controllers::loans_page))
                    .route("/loans/apply", web::get().to(controllers::loan_apply_page))
                    .route("/loans/apply", web::post().to(controllers::create_personal_loan))
                    .route("/loans/{id}/pay", web::post().to(controllers::pay_loan))
                    .route("/home-loans", web::get().to(controllers::home_loans_page))
                    .route("/home-loans/apply", web::get().to(controllers::home_loan_apply_page))
                    .route("/home-loans/apply", web::post().to(controllers::create_home_loan_application))
                    .route("/home-loans/{id}/pay", web::post().to(controllers::pay_home_loan))
                    .route("/fixed-deposits", web::get().to(controllers::fixed_deposits_page))
                    .route("/fixed-deposits", web::post().to(controllers::create_fixed_deposit))
                    .route("/fixed-deposits/new", web::get().to(controllers::fixed_deposit_new_page))
                    .route("/fixed-deposits/{id}/withdraw", web::post().to(controllers::withdraw_fixed_deposit))
                    .route("/profile", web::get().to(controllers::profile_page))
                    .route("/profile", web::post().to(controllers::update_profile)),
            )
            .service(
                web::scope("/admin")
                    .route("/login", web::get().to(controllers::admin_login_page))
                    .route("/login", web::post().to(controllers::admin_login))
                    .route("/logout", web::get().to(controllers::admin_logout))
                    .route("", web::get().to(controllers::admin_dashboard))
                    .route("/dashboard", web::get().to(controllers::admin_dashboard))
                    .route("/signups", web::get().to(controllers::admin_signups_page))
                    .route("/onboardings", web::get().to(controllers::admin_signups_page))
                    .route("/onboardings/{id}/approve", web::post().to(controllers::approve_customer_application))
                    .route("/onboardings/{id}/reject", web::post().to(controllers::reject_customer_application))
                    .route("/signups/{id}/approve", web::post().to(controllers::approve_customer_application))
                    .route("/signups/{id}/reject", web::post().to(controllers::reject_customer_application))
                    .route("/staff", web::get().to(controllers::admin_staff_page))
                    .route("/staff", web::post().to(controllers::create_staff_user))
                    .route("/staff/{id}/update", web::post().to(controllers::update_staff_user))
                    .route("/staff/{id}/delete", web::post().to(controllers::delete_staff_user))
                    .route("/accounts", web::get().to(controllers::admin_customer_accounts_page))
                    .route("/accounts/users/{id}/suspend", web::post().to(controllers::suspend_customer_user))
                    .route("/accounts/users/{id}/activate", web::post().to(controllers::activate_customer_user))
                    .route("/accounts/products/{id}/activate", web::post().to(controllers::activate_customer_product))
                    .route("/accounts/products/{id}/freeze", web::post().to(controllers::freeze_customer_product))
                    .route("/accounts/products/{id}/close", web::post().to(controllers::close_customer_product))
                    .route("/high-value-monitoring", web::get().to(controllers::admin_high_value_monitoring_page))
                    .route("/high-value-monitoring/{id}/status", web::post().to(controllers::update_high_value_alert_status))
                    .route("/audit-log", web::get().to(controllers::admin_audit_log_page))
                    .route("/personal-loans", web::get().to(controllers::admin_personal_loans_page))
                    .route("/personal-loans/{id}/approve", web::post().to(controllers::approve_personal_loan))
                    .route("/personal-loans/{id}/reject", web::post().to(controllers::reject_personal_loan))
                    .route("/home-loans", web::get().to(controllers::admin_home_loans_page))
                    .route("/home-loans/{id}/approve", web::post().to(controllers::approve_home_loan))
                    .route("/home-loans/{id}/reject", web::post().to(controllers::reject_home_loan))
                    .route("/fixed-deposits", web::get().to(controllers::admin_fixed_deposits_page))
                    .route("/fixed-deposit-plans", web::get().to(controllers::admin_fixed_deposit_plans_page))
                    .route("/fixed-deposit-plans", web::post().to(controllers::create_fixed_deposit_plan))
                    .route("/fixed-deposit-plans/{id}", web::post().to(controllers::update_fixed_deposit_plan)),
            ),
    );
}
